apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sda8ymmqn-nodejs 
  janus-idp.io/tekton: sda8ymmqn-nodejs
  backstage.io/kubernetes-id: sda8ymmqn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sda8ymmqn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml