apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sda8ymmqn-nodejs
  janus-idp.io/tekton: sda8ymmqn-nodejs
  backstage.io/kubernetes-id: sda8ymmqn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sda8ymmqn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
