apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sda8ymmqn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8f8ad35e40.kgz7.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:749a90d9c904f80d223e0ab5203a40744aa272d0@sha256:37de067acea6de1d65df69f26caf9f74ed60765d0c2b9126830038a558c51ba1
          name: container-image
